Update __init__.py
ImportError: attempted relative import with no known parent package

The . indicates that the import statement is relative to the current package.

but I am still getting the error,  so I try using an absolute import statement instead of a relative import statement, which means remove the '.'